#! /bin/bash

echo 'Creating virtual-env...'
sudo apt-get install python3 python3-venv
/usr/bin/python3 -m venv .venv 
source .venv/bin/activate

echo 'Installing dependencies...'
pip install --upgrade pip
.venv/bin/pip install -r requirements.txt
