#! /bin/bash

if [ -d ".venv/bin/" ] 
then  
    source .venv/bin/activate

    # FIXME: make sure bluetooth tether connected

    # FIXME: remove this line:
    export SERIAL_NUMBER="21AH250C99EV34"

    # Initialize ENV
    echo "SERVER_HOST=192.168.0.10" > .env
    echo "SERVER_PORT=8000" >> .env
    echo "SERIAL_NUMBER=$SERIAL_NUMBER" >> .env
    echo "PUBLIC_IP=$(curl ifconfig.me)" >> .env
    echo "DEVICE_NAME=$hostname" >> .env
    echo "DEVICE_CODE=AE45980" >> .env

    # Start program
    .venv/bin/python app/main.py
else
    echo "Error: Startup failed because '.venv/bin/python' does not exists."
    echo "Error: Try running './setup' first or ensure venv is activated with 'source .venv/bin/activate"
fi

