#! /bin/bash

if [ -d ".venv/bin/" ] 
then  
    source .venv/bin/activate
    echo "SERVER_HOST=192.168.0.20" >> .env
    echo "SERVER_PORT=8000" >> .env
    echo "SERIAL_NUMBER=$SERIAL_NUMBER" >> .env
    echo "PUBLIC_IP=$(curl ifconfig.me)" >> .env
    .venv/bin/python app/main.py
else
    echo "Error: Startup failed because '.venv/bin/python' does not exists."
    echo "Error: Try running './setup' first or ensure venv is activated with 'source .venv/bin/activate"
fi

