services:
  client:
    build: ./client
    restart: unless-stopped
    ports:
      - 3000:3000
  api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    build: ./db
    restart: unless-stopped
    command: mysqld --authentication_policy=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - ./db/database.env
    volumes:
      - db-data:/etc/data

volumes:
  db-data:
    external: true