services:
  client:
    build: ./client
    restart: unless-stopped
    ports:
      - 3000:3000
  api:
    command: sh -c "sleep 2; uvicorn app.main:app --host 0.0.0.0 --port 8000"
    build: ./api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    build: ./db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./db/database.env

volumes:
  db-data:
    external: true